// <auto-generated />
using System;
using Game.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Game.Migrations
{
    [DbContext(typeof(GameDb))]
    partial class GameDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("Game.Entity.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FoodAdd")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FoodCost")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("FoodModificator")
                        .HasColumnType("REAL");

                    b.Property<int?>("GoldAdd")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GoldCost")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("GoldModificator")
                        .HasColumnType("REAL");

                    b.Property<int?>("HumanAdd")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HumanCost")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("HumanModificator")
                        .HasColumnType("REAL");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaterialsAdd")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaterialsCost")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MaterialsModificator")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nextlevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Requirement1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Requirement2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Requirement3")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ValueRequirement1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ValueRequirement2")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ValueRequirement3")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Buildings");
                });
#pragma warning restore 612, 618
        }
    }
}
